dbt_demo:
  outputs:
    dev:
      dbname: dbt
      host: localhost
      port: 5432
      schema: dbt 
      threads: 10
      type: postgres
      user: _user_ 
      pass: _password_
  target: dev