dbt_demo:
  outputs:
    dev:
      type: athena
      s3_staging_dir: s3://staging/
      s3_data_dir: s3://data/
      # s3_data_naming: [table_unique] # the type of naming convention used when writing to S3
      region_name: us-east-1
      database: default
      schema: test
      # aws_profile_name: [optional profile to use from your AWS shared credentials file.]
      threads: 1
      num_retries: 0
  target: dev