on: [push]

jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: A job to say hello
    steps:
      - name: Checkout
        uses: actions/checkout@v5
      - name: dbt-action
        uses: mwhitaker/dbt-action@master
        with:
          dbt_command: "dbt deps"
      - name: dbt-action
        uses: mwhitaker/dbt-action@master
        with:
          dbt_command: "dbt test"
