on: [push]
# based on https://docs.github.com/en/actions/tutorials/use-containerized-services/create-a-docker-container-action
jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: A job to say hello
    steps:
      - name: Checkout
        uses: actions/checkout@v5
      - name: Get the output time
        run: make test
